name: Build Bitcoin Wallet - main
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code (nhánh main của bạn)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platform-tools platforms;android-34 build-tools;34.0.0'

      - name: Setup Gradle (dùng wrapper trong repo)
        uses: gradle/actions/setup-gradle@v3

      - name: Kiểm tra file
        run: ls -la

      - name: Build APK prodDebug
        run: |
          chmod +x gradlew
          ./gradlew :wallet:assembleProdDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: bitcoin-main-apk
          path: wallet/build/outputs/apk/prod/debug/*.apk
