name: Freeze My Repo
on:
  workflow_dispatch:

jobs:
  freeze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Check repo
        run: |
          test -f gradlew || (echo "THIEU gradlew" && exit 1)
          test -d wallet || (echo "THIEU thu muc wallet" && exit 1)
          ls -lh

      - name: Build offline cache
        run: |
          chmod +x gradlew
          ./gradlew :wallet:dependencies --no-daemon --stacktrace

      - name: Force download
        run: ./gradlew :wallet:assembleDebug --no-daemon || true

      - name: Pack cache
        run: tar -czf my-offline.tar.gz -C $HOME .gradle

      - uses: actions/upload-artifact@v4
        with:
          name: my-offline-cache
          path: my-offline.tar.gz