- name: Force libs for Gradle 6
  run: |
    mkdir -p ~/.gradle/init.d
    cat > ~/.gradle/init.d/force.gradle <<'EOF'
    allprojects {
      configurations.all {
        exclude group: 'com.google.guava', module: 'listenablefuture'
        resolutionStrategy {
          force 'com.google.guava:guava:31.1-android'
          eachDependency { d ->
            if (d.requested.group.startsWith('androidx.core')) { d.useVersion '1.12.0' }
            if (d.requested.group == 'androidx.annotation' && d.requested.name == 'annotation') { d.useVersion '1.7.0' }
            if (d.requested.group == 'androidx.annotation' && d.requested.name == 'annotation-experimental') { d.useVersion '1.3.1' }
            if (d.requested.group == 'androidx.arch.core') { d.useVersion '2.2.0' }
            if (d.requested.group == 'androidx.fragment') { d.useVersion '1.6.2' }
            if (d.requested.group == 'androidx.activity') { d.useVersion '1.8.1' }
            if (d.requested.group == 'androidx.appcompat') { d.useVersion '1.6.1' }
            if (d.requested.group == 'androidx.lifecycle') { d.useVersion '2.6.2' }
            if (d.requested.group == 'androidx.viewpager2') { d.useVersion '1.0.0' }
            if (d.requested.group == 'androidx.recyclerview') { d.useVersion '1.3.2' }
          }
        }
      }
    EOF